version: '3.8'

services:
  catalogdb:
    image: postgres:16-alpine
    container_name: catalogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    restart: on-failure

volumes:
  postgres_catalog:

